### ISSUE TITLE
src/game/chat doesn't exist?

### ISSUE THREAD

**Issue by BitesizedLion** [dannytech/Elytra#4]
Hi, the repository is missing 4 files.

```
src/protocol/states/login/DisconnectPacket.ts:3:31 - error TS2307: Cannot find module '../../../game/chat/ChatComponent' or its corresponding type declarations.

3 import { ChatComponent } from "../../../game/chat/ChatComponent";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/protocol/states/login/EncryptionResponsePacket.ts:14:38 - error TS2307: Cannot find module '../../../game/chat/ChatComponentFactory' or its corresponding type declarations.

14 import { ChatComponentFactory } from "../../../game/chat/ChatComponentFactory";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/protocol/states/play/DisconnectPacket.ts:3:31 - error TS2307: Cannot find module '../../../game/chat/ChatComponent' or its corresponding type declarations.

3 import { ChatComponent } from "../../../game/chat/ChatComponent";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/protocol/states/status/ResponsePacket.ts:5:38 - error TS2307: Cannot find module '../../../game/chat/ChatComponentFactory' or its corresponding type declarations.

5 import { ChatComponentFactory } from "../../../game/chat/ChatComponentFactory";
```

**Comment by dannytech** [comment]
Hey, thanks for checking out the project, didn't think anybody would be interested in it. I haven't worked on it in a while, but I was last working on ChatComponents, specifically writing a parser that converts the [formatting codes](https://minecraft.gamepedia.com/Formatting_codes) to JSON structures that the client also accepts, so that I could write formatted messages easily. The parser isn't currently working properly because I'm terrible at debugging parsers, but I'll push the code I have written for it to a new branch, `chat`. I haven't tested it so it might just give a weird output, if it errors let me know and I can probably whip up a stub function that just wraps the input in the correct JSON.

**Comment by BitesizedLion** [comment]
> 
> 
> Hey, thanks for checking out the project, didn't think anybody would be interested in it. I haven't worked on it in a while, but I was last working on ChatComponents, specifically writing a parser that converts the [formatting codes](https://minecraft.gamepedia.com/Formatting_codes) to JSON structures that the client also accepts, so that I could write formatted messages easily. The parser isn't currently working properly because I'm terrible at debugging parsers, but I'll push the code I have written for it to a new branch, `chat`. I haven't tested it so it might just give a weird output, if it errors let me know and I can probably whip up a stub function that just wraps the input in the correct JSON.

That does indeed work,

**Comment by dannytech** [comment]
Just adding a comment to say that the parser has been updated and is now fully functional given valid formatting [codes](https://minecraft.fandom.com/wiki/Formatting_codes), either using `§` or `&`. The `main` branch should run fine now that it's been included.
